# Generated by Django 5.0.1 on 2024-01-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_alter_contacts_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='user_id',
        ),
    ]
